### ISSUE TITLE
Не отображается перенос строки в шагах воспроизведения и ожидаемом результате

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#121]
Шаги воспроизведения:
1. Перейти на страницу создания тест-кейса
2. Нажать на кнопку "Add Step"
3. Заполнить поле "Step" данными с переносом строки
4. Нахать на кнопку "Save"
5. Обратить внимание на созданный шаг

Фактический результат:
Перенос строки отсутсвует, данные отображаются в одну строку. При этом, если открыть шаг на редактирование, то в текстовом поле данные будут отображаться так же, как при их введении, то есть с переносом.

Ожидаемый результат:
Данные отображаются так же, как при введении. 

![2021-06-01_10-52-53](https://user-images.githubusercontent.com/69976993/120280158-66455680-c2c8-11eb-9c84-f6d36669f65f.png)
![2021-06-01_10-53-28](https://user-images.githubusercontent.com/69976993/120280178-6c3b3780-c2c8-11eb-8811-49edf0c876db.png)

**Comment by azee** [comment]
Fixed in master. Out next release.

**Comment by azee** [comment]
Released
