### ISSUE TITLE
Выделение на ввыбранном тест-кейсе закрывает дропдауны

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#122]
Шаги воспроизведения:
1. Перейти на страницу /testcases
2. Выбрать первый тест-кейс в списке
3. Нажать на любой из выпадающих списков
4. Обратить внимание на список

Фактический результат:
Выделение на выбранном тест-кейсе закрывает выпадающий список

Ожидаемый результат:
Выделение не закрывает выпадающие списки

![2021-06-01_10-53-58](https://user-images.githubusercontent.com/69976993/120280619-f97e8c00-c2c8-11eb-96ad-51f8c1f9ee94.png)

**Comment by azee** [comment]
Fixed in master. Out next release.

**Comment by azee** [comment]
Released
