### ISSUE TITLE
В превью добавленного файла отсутствуют иконки кнопок

### ISSUE THREAD

**Issue by DinaKry** [greatbit/quack#125]
**Шаги**
1. Прикрепить файл к кейсу
2. Обратить внимание на кнопки в правом нижнем углу

**Результат**
Все кнопки выглядят одинаково, иконок нет 
![Снимок экрана 2021-06-15 114330](https://user-images.githubusercontent.com/85930213/122022121-f73f2600-cdce-11eb-86b9-fac18fd29137.png)

**Comment by azee** [comment]
Fixed and released in 1.8
