### ISSUE TITLE
Обновление страницы сбрасывает введенные данные

### ISSUE THREAD

**Issue by DinaKry** [greatbit/quack#127]
Нужно, чтобы при обновлении страницы введенные, но не сохраненные данные оставались в поле ввода (например, в шаге кейса)

**Comment by karevn** [comment]
Если речь идёт о каких-нибудь фильтрациях и сортировках списков -- то это надо будет обязательно сделать, это улучшит как код, так и юзабилити. 

Если же речь о заполнении форм, то скорее всего это будет сделано когда-нибудь очень нескоро, потому что техническая сложность перевешивает полезность.

**Comment by azee** [comment]
Фильтрация и группировка и так презёрвится в URL - когда меняешь фильтры - меняется и URL. Соответственно, по этому URL восстанавливаются фильтры - можно обновить страницу или кинуть ссылку коллеге

**Comment by azee** [comment]
Released in 1.10 - all reach text editors will alert if you re-load without saving
