### ISSUE TITLE
При редактировании атрибута изменение не применяется к тест-кейсам, в которых ранее был использован этот атрибут

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#129]
Шаги воспроизведения:
1. Создать атрибут
2. Создать тест-кейс с ранее созданным атрибутом
3. Отредактировать атрибут
4. Обратить внимание на атрибут в ранее созданным тест-кейсе

Фактический результат:
Атрибут в ранее созданном кейсе не изменился

Ожидаемый результат:
Атрибут в ранее созданном кейсе изменился

Видео: https://yadi.sk/i/mw_CQHLDZKxHBQ

**Comment by azee** [comment]
There is no testcase processing for deletion either. Working on it.

**Comment by azee** [comment]
Fixed in master. Out next release.

**Comment by azee** [comment]
Fixed in 1.7

**Comment by DinaKry** [comment]
Сейчас в ранее созданном кейсе все значения измененного атрибута удаляются
