### ISSUE TITLE
Подтверждение удаления шагов в тест-кейсах

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#130]
Сейчас возможно удалить шаг в тест-кейсе просто кликунв по кнопке "Remove", что оставляет возможность случайного удаления. 
![2021-06-17_20-37-39](https://user-images.githubusercontent.com/69976993/122438774-2068dd80-cfac-11eb-8c4c-d1ec095aba04.png)
Для исключения этой возможности необходимо сделать модалку - подтверждение действия, как в случае с удалением тест-кейса.
![image](https://user-images.githubusercontent.com/69976993/122438822-2bbc0900-cfac-11eb-9a3a-0e6a26519e5f.png)

**Comment by azee** [comment]
Fixed and released in 1.6
