### ISSUE TITLE
Атрибут дублируется на странице управления атрибутами при сохранении изменений

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#131]
Шаги воспроизведения:
1. Перейти на страницу управления атрибутами `/{project}/attributes`
2. Нажать на карандаш 
3. В открывшемся поп-апе отредактировать любое из полей и нажать на кнопку "Save changes"
4. Обратить внимание на список атрибутов

Фактический результат:
Отредактированный атрибут дублируется

Ожидаемый результат:
Отредактированный атрибут не дублируется

Видео: 
https://yadi.sk/i/IKyBi_chRdaU7g

**Comment by azee** [comment]
Fixed and released in 1.6
