### ISSUE TITLE
Тест-кейсы не всегда отображаются на экране лаунча

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#132]
Баг плавающий, сценарий для 100% воспроизведения найти не удалось, по этому, возможно придется повторить шаги воспроизведения >1 раза.

Предусловие:
Должно быть создано >= 1 тест-кейс(ов)

Шаги воспроизведения:
1. Перейти на страницу Test Cases
2. Нажать на кнопку Launch
3. В открывшемся поп-апе заполнить поле Name и нажать на кнопку "Create Launch"
4. Нажать на кнопку "Go to launch"
5. Обратить внимание на отсутствие тест-кейсы и всплывающий алерт с текстом "Couldn't get launch:"

_Комментарий: Что бы не воспроизводить каждый раз все шаги, в случае, если с первого раза баг не воспроизвелся, отлично помгает обновление страницы без кэша, `CTRL + F5`._

Фактический результат:
Тест-кейсы не отображаются, появляется алерт с текстом "Couldn't get launch:"

Ожидаемый результат:
Тест-кейсы отображаются

Видео:
https://yadi.sk/i/MolDmHPt0obIZQ

**Comment by azee** [comment]
Fixed and released in 1.6
