### ISSUE TITLE
Форматирование текста

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#138]
Нужна возможность форматировать текст:
1. Тонкий
2. Жирный
3. Курсив
4. Список
5. Список числовой
6. Вставка кода
7. Гиперссылка.

Так же нужна возможность строить в шагах тест-кейсов примитивные таблицы

**Comment by azee** [comment]
Implemented and merged to master. Will be released in 1.9.

**Comment by azee** [comment]
Released in 1.9
