### ISSUE TITLE
Вложенность тест-кейсов в папки

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#140]
При работе с большими обьемами тест-кейсов появляется необходимость в систематизации набора. Эту проблему легко решить по вредствам создания папок\категорий и подпапок\подкатегорий в списке тест-кейсов проекта. Прикладываю скрины референса, для верного понимания, что имею в виду:
![2021-06-24_14-35-20](https://user-images.githubusercontent.com/69976993/123248876-77fdd080-d4f9-11eb-8f88-5920d5895a52.png)
Что бы было удобнее взаимодействовать, должна быть возможность сворачивания и разворачивания папки. Для удобной навигации в прогонах нужно что бы вложенность в списке тест-кейсов сохранялась.

**Comment by azee** [comment]
Это же как раз решается группировкой по аттрибутам.
В тесткейсе задаёте аттрибуты.
Например, в данном случае будет что-то вроде:

Атрибут "Раздел", значения атрибута: "Редактирование группы", "Что-то ещё - не видно на скрине :) "
Атрибут "Функциональность" со значениями: "Аоны", "Сигналы"

Проставляете тесткейсам эти аттрибуты.

Дальше идём в список тесткейсов и там в grouping выбираем последовательно атрибуты "Раздел" и "Функциональность". В результате получаете дерево - как на скрине.

Можно наоборот дерево развернуть, можно сделать только из "Раздел" или только "Функциональность".

Атрибутов может быть больше, соответственно и дерево можно строить таким образом глубже и как угодно перемешивать последовательность группировки
