### ISSUE TITLE
Не работает скролл в списке тест-кейсов и при просмотре тест-кейса

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#156]
Шаги воспроизведения:
1. Перейти на страницу тест-кейсов
2. Попробовать проскролить список тест-кейсов
3. Открыть тест-кейс
4. Попробовать проскролить тест-кейс

Фактический результат:
Список тест-кейсов и сам тест-кейс не скролится, скролбар замьючен

Ожидаемый результат:
Список тест-кейсов и тест-кейс скролится

![2021-09-13_19-58-18](https://user-images.githubusercontent.com/69976993/133117302-32797abb-4f12-4887-bea8-4b43c84c679c.png)

**Comment by azee** [comment]
Подскажите, пожалуйста, что за браузер?

**Comment by Philya-gross** [comment]
@azee Fierfox 91.0.1 Chrome 93.0.4577.63

**Comment by azee** [comment]
А сама страничка целиком же скроллится? 
Видимо, это Windows. На маках просто нет этих скроллов.
Как было бы удобнее - скрыть эти скроллы и скроллить всю страницу целиком, или скроллить каждый кусок по-отдельности?

**Comment by azee** [comment]
Сделал раздельные скроллы, так будет удобнее имхо. Выедет в ближайшем релизе
