### ISSUE TITLE
Огромные межстрочные интервалы во всех полях тест-кейсов

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#158]
Шаги воспроизведения:
1. Перейти на страницу тест-кейсов
2. Открыть тест-кейс
3. Обратить внимание на междстрочние интервалы в примечании, предусловии и шагах тест-кейсов

Фактический результат:
Межстрочный интервал очень большой, из-за этого с тест-кейсами не удобно работать.

Ожидаемый результат:
Межстрочный интервал разумного размера. 

![2021-09-13_20-42-03](https://user-images.githubusercontent.com/69976993/133123658-0da85022-5ac9-408f-9a43-fb262fb40b7b.png)
![2021-09-13_20-41-44](https://user-images.githubusercontent.com/69976993/133123662-0f1c00f6-73c4-47a7-b54b-ee27e335c3c9.png)

**Comment by azee** [comment]
В мастере. Выедет ближайшим релизом

**Comment by azee** [comment]
Released in 1.12
https://github.com/greatbit/quack/releases/tag/quack-1.12
