### ISSUE TITLE
"Фантомный" атрибут Broken

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#159]
Шаги воспроизведения:
1. Перейти на страницу тест-кейсов
2. Выбрать тест кейс
3. Нажать на кнопку "Add Attribute"
4. Обратить внимание на атрибут broken

Фактический результат:
В списке атрибутов есть автрибут Broken, хотя у проекта не заведен такой атрибут

Ожидаемый результат:
В списке атрибутов есть только те атрибуты, что были заведены для конкретного проекта

![2021-09-13_20-44-05](https://user-images.githubusercontent.com/69976993/133124193-dfce8dd3-271c-40ff-851d-da0475cbb166.png)
![2021-09-13_20-43-32](https://user-images.githubusercontent.com/69976993/133124207-93b52a49-5ffc-4409-a73c-15a5bc7a12a8.png)

**Comment by azee** [comment]
Это не фантомный атрибут. Он нужен для того, чтобы помечать сломанные тесты и потом по ним фильтровать.
Собственно, ползунок On/Off на тесткейсе им и оперирует.
Я просто уберу его из списка атрибутов в данном месте

**Comment by azee** [comment]
Убрал его из формы в тесткейсе. Выедет в ближайшем релизе

**Comment by azee** [comment]
Released in 1.12
https://github.com/greatbit/quack/releases/tag/quack-1.12
