### ISSUE TITLE
Курсор при наведении на блок кода в теле тест-кейса не становится поинтером

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#160]
Шаги воспроизведения:
1. Перейти на страницу тест-кейсов
2. Создать тест кейс, в тело одного из шагов добавить блок кода
3. Навести на блок кода курсор
4. Обратить внимание на курсор
5. Кликнуть один раз на блок кода

Фактический результат:
При наведении курсор не меняется, после одного клика курсор визуально становится заблокированным, хотя при двойном клике на блок кода откроется его редактор

Ожидаемый результат:
Курсор становится поинтером при наведении на блок кода, редактор кода открывается при однократном клике на блок кода.

**Comment by azee** [comment]
Это дефолтное поведение TinyMCE - библиотеки Rich Text Edition.
И, как мне кажется, это вполне оправдано. Двойной клик тут несколько более очевиден, т.к. одиночный даёт возможность выделить объект, перетащить его. 
Курсор заблокирован при первом клике, т.к. блок кода в терминах TinyMCE считается нередактируемым Inplace, а редактируется при двойном клике в отдельном модале.
