### ISSUE TITLE
После нажатия на кнопку Load More в списке тест-кейсов перестает рабоотать фильтрация

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#162]
Предусловие: 
В проекте более 50 тест-кейсов

Шаги воспроизведения:
1. Перейти на страницу тест-кейсов
2. Нажать на кнопку Load more 
3. Попробовать отфильтровать тест-кейсы

Фактический результат:
При фильтрации после нажатия на кнопку Load more все тест-кейсы пропадают

Ожидаемый результат:
Тест-кейсы не пропадают при фильтрации

![2021-09-13_21-07-28](https://user-images.githubusercontent.com/69976993/133126911-60b01bcc-007f-4f81-9daa-b2c9881de4b2.png)

**Comment by azee** [comment]
Nice catch. Out in upcoming release.

**Comment by azee** [comment]
Released in 1.12
https://github.com/greatbit/quack/releases/tag/quack-1.12
