### ISSUE TITLE
При работе с лаунчем не из под root-юзера при изменении статуса кейса возвращается 403 ошибка.

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#167]
Шаги воспроизведения:
1. Залогиниться под любым пользователем кроме root
2. Создать лаунч
3. Попробовать поменить тест-кейс любым статусом. Passed, failed, skip
4. Обратить внимание на ошибку в правом верхнем углу

Фактический результат:
Статус не проставляется, 403 ошибка

Ожидаемый результат:
Спатус проставляется
![2021-09-15_20-27-38](https://user-images.githubusercontent.com/69976993/133473371-e3ca9020-ae66-4289-b9cd-fdc168149338.png)

**Comment by azee** [comment]
Исправлено в мастере. Выедет в ближайшем релизе

**Comment by azee** [comment]
Released in 1.12
https://github.com/greatbit/quack/releases/tag/quack-1.12
