### ISSUE TITLE
У любого пользователя, кроме юзера root, не отображаются проекты в дропдауне

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#168]
Шаги воспроизведения:
1. Залогиниться под любым пользователем кроме root
2. Кликнуть на дропдаун с проектами

Фактический результат:
Ни одного проекта в дропдауне, хотя доступы к проектам есть

Ожидаемый результат:
В дропдауне проекты к которым у пользователя есть доступ
![2021-09-15_20-34-36](https://user-images.githubusercontent.com/69976993/133473816-2f05c42a-cf8d-4159-af42-9932db2b16b8.png)

**Comment by azee** [comment]
Исправлено в масетере. Выедет в ближайшем релизе

**Comment by azee** [comment]
Released in 1.12
https://github.com/greatbit/quack/releases/tag/quack-1.12
