### ISSUE TITLE
Если создать лаунч из сгруппированных кейсов, то шаги и предусловия не отобрадаются в кейсах из лаунча

### ISSUE THREAD

**Issue by Philya-gross** [greatbit/quack#172]
Шаги воспроизведения:
1. Перейти на страницу с тест кейсами 
2. Сгруппировать тест-кейсы по какому-нибудь атрибуту
3. Создать лаунч
4. Обратить внимание на наполнение тест-кейсов в лаунче

Фактический результат:
Предусловие, шаги  воспроизведения и атрибуты отсутствуют

Ожидаемый результат:
Предусловие, шаги и атрибуты видно 

Видео: https://yadi.sk/i/wdp2Zc9gWrr3WA

**Comment by azee** [comment]
The problem is that for tree view we are using TestcasePreview object. We have to modify the model so that Testcase will implicitly inherit TestacsePreview.
Will fix it in the upcoming release.

**Comment by azee** [comment]
Fix released in 1.16
