### ISSUE TITLE
No Statistics link on Launches page

### ISSUE THREAD

**Issue by JoeFengZhou** [greatbit/quack#188]
**Is your feature request related to a problem? Please describe.**
As per the demo of QuAck, there is a Statistics link on the Launches page. However the QuAck free-trial cloud service doesn't have
this link.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Please find a screenshot for the Launches page of QuAck free-trial.
![Screenshot (164)](https://user-images.githubusercontent.com/98251226/150873312-e5c23515-39ca-4e18-b180-63a9b4941725.png)

**Comment by azee** [comment]
This is expected in the cloud at the moment. We are going to migrate to a different database instance types - those that support map-reduce - this weekend. Will be re-enabling statistics right after that.

**Comment by JoeFengZhou** [comment]
Thank you very much Azee for your prompt reply.

**Comment by azee** [comment]
@JoeFengZhou 
Hi Joe.
Migration is complete and statistic is now available in the cloud.
