### ISSUE TITLE
AliExpress transition from the order card to the product description

### ISSUE THREAD

**Issue by robertpetrosian** [greatbit/quack#192]
**Error 404 when transition from the paid nonshipped order card to the product description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by azee** [comment]
Hi @robertpetrosian 
Please clarify the issue. From my understanding it is related to AliExpress, not the QuAck.
