### ISSUE TITLE
Каким образом подключается import-maven-plugin?

### ISSUE THREAD

**Issue by krkub3** [greatbit/quack#205]
QuAck установлен на standalone сервер.
Нужно подключить к нему [import-maven-plugin](https://github.com/greatbit/import-maven-plugin).
Как это сделать?
Я собрал плагин с помощью maven. Получил три файла:
```
target/import-maven-plugin-1.3-SNAPSHOT.jar
target/import-maven-plugin-1.3-SNAPSHOT-javadoc.jar
target/import-maven-plugin-1.3-SNAPSHOT-sources.jar
```
Это и есть плагин? Как подключить эти файлы к QuAck?

**Comment by azee** [comment]
Плагин сам собирать не надо - это Maven Plugin - плагин для Maven-а.
Он умеет при выполнении мавена импортировать сами тесты и результаты выполнения в QuAck.
Плагин подключается к вашим тестам

https://github.com/greatbit/import-maven-plugin - тут описано, как добавить plugin в POM-файл вашего проекта с тестами.

Вот конкретный пример (тесты выполняются в serverless-облаке при помощи Smith, но это - не важно)
https://github.com/greatbit/smith-junit-maven-tests-example/blob/master/pom.xml#L46-L89
