### ISSUE TITLE
При создании лаунча, в него попадают невыбранные кейсы.

### ISSUE THREAD

**Issue by Vladisvalov** [greatbit/quack#206]
1. Логинемся под рутом.
2. Создаём новый пустой раздел.
3. Добавляем два кейса: 1 и 2
4. Снимаем с первого чекбокс и нажимаем Launch
5. Вводим имя лаунчу и нажимаем Create
6. Переходим в лаунч
Ожид.рез: в лануче один кейс.
Факт.рез: в лаунче все кейсы проекта.

https://youtu.be/QoMxT7c-N5U

**Comment by azee** [comment]
Удалённые тесткейсы попадают в ланч

**Comment by azee** [comment]
Fixed in https://github.com/greatbit/quack/releases/tag/quack-1.17
