### ISSUE TITLE
При создании Лаунча с группировкой по разделу и подразделу, раздел и подраздел перемешиваются. 

### ISSUE THREAD

**Issue by Vladisvalov** [greatbit/quack#208]
1. Логинемся под рутом.
2. Создаём новый пустой раздел.
3. Добавляем два кейса: 1 и 2
4. Добавляем в проект атрибуты: Раздел: Название Раздела, Подраздел: Название подраздела.
5. Присваиваем их кейсам.
6. Делаем группировку по "Раздел", "Подраздел"
7. Выбираем все кейсы.
8. Нажимаем Launche
9. Вводим имя лаунчу и нажимаем Create
10. Переходим в лаунч
Ожид.рез: Не перемешаны разделы и подразделы.
Факт.рез: Они перемешаны.
**Видео:** https://youtu.be/M8_bIHD1X50

**Comment by azee** [comment]
Fixed in https://github.com/greatbit/quack/releases/tag/quack-1.17
