### ISSUE TITLE
Явно выделить id кейса

### ISSUE THREAD

**Issue by Vladisvalov** [greatbit/quack#218]
При использовании группировки кейсов, сложно понять, какой у кейса id.
Добавить в описании точный id.
![image](https://user-images.githubusercontent.com/32393506/170956379-530e234c-d04e-491e-83db-739bd7f02e80.png)

**Comment by azee** [comment]
Закоммитил в мастер. Выедет в ближайшем релизе

**Comment by azee** [comment]
Released in 1.19
https://github.com/greatbit/quack/releases/tag/quack-1.19
