### ISSUE TITLE
Добавить поиск по названию кейса, среди всех кейсов проекта.

### ISSUE THREAD

**Issue by Vladisvalov** [greatbit/quack#220]
![image](https://user-images.githubusercontent.com/32393506/171807468-3bfee145-01f9-490a-a0c9-ecb0dc7a9810.png)
Иногда, когда нужно найти конкретный, даже искать через группировку, уходит много времени, это бы очень помогло.

**Comment by azee** [comment]
Закоммитил фикс. Выедет в ближайшем релизе

**Comment by azee** [comment]
Released in 1.19
https://github.com/greatbit/quack/releases/tag/quack-1.19
