### ISSUE TITLE
В лаунче у кейсов отсутствуют атрибуты и свойства. 

### ISSUE THREAD

**Issue by Vladisvalov** [greatbit/quack#221]
После запуска лаунча по заданным фильтрам отсутствуют атрибуты и свойства. 
![image](https://user-images.githubusercontent.com/32393506/171810628-9fffa01a-5d8c-41e8-aca6-c954af4fec7b.png)
При этом, по факту они есть.

**Comment by azee** [comment]
Закоммитил фикс. Выедет в ближайшем релизе

**Comment by azee** [comment]
Released in 1.19
https://github.com/greatbit/quack/releases/tag/quack-1.19
