### ISSUE TITLE
Only shows 20 launches

### ISSUE THREAD

**Issue by mpelley** [greatbit/quack#232]
I have a project with 139 launches.  The launches tab only shows 20.  The "next page" button is disabled.  I suspect this is because the API request for a count of launches has a "limit=20" parameter in the request, so the response is "20" instead of "139".  If I send the request without this parameter, the count is "139".

1. Create a project with more than 20 launches.
2. Go to the launches tab
3. Observe the "next page" button is disables, so you can't ever see the rest of the launches.

I am using the version in GitHub (October 2022?).

**Comment by azee** [comment]
Fix pushed to master. Out in upcoming release

**Comment by azee** [comment]
Released within
