### ISSUE TITLE
Exception in monitor thread while connecting to mongod:27017

### ISSUE THREAD

**Issue by bobbeck55** [greatbit/quack#237]
**Describe the bug**
Quack has a problem connecting to server mongod:27017

**To Reproduce**
Ubuntu 22.04
cd quack
docker-compose -f docker-compose.yml up

**Expected behavior**
quack should start up and allow new users and test cases to be added.
An attempt is made to add a new user.

**Screenshots**
Actually, when quack attempted to connect to the mongod, there was
an exception thrown. Seen screenshot.
![image](https://user-images.githubusercontent.com/107821526/218897265-b7447903-c577-4f3f-9fbb-7bb3c70b9102.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by azee** [comment]
@bobbeck55 Can you please send the whole log? There should be mongo starting logs prior to QuAck app

**Comment by azee** [comment]
@bobbeck55 Please try pulling the latest changes. https://github.com/greatbit/quack/commit/e94e800b5d6dd755ea4ca9c41c1e0c0227017bd8 might help.

If not - please send me the whole compose log including mongo

**Comment by bobbeck55** [comment]
I pulled the latest changes and used the same docker command as before. Log doesn't want to attach. I'll send attached to an email.

**Comment by bobbeck55** [comment]
[quack_up_log.txt](https://github.com/greatbit/quack/files/10744576/quack_up_log.txt)
Here's the log

**Comment by bobbeck55** [comment]
I attached the log to issue 237 in github

**Comment by azee** [comment]
@bobbeck55 Log says:  
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
[36mmongod    |[0m   see https://jira.mongodb.org/browse/SERVER-54407

Probably Mongo 5 that is specified in the compose won't work on your machine. Try changing this line locally
https://github.com/greatbit/quack/blob/master/docker-compose.yml#L15
from
image: mongo:5
to 
image: mongo:4.2

And try running compose again

**Comment by bobbeck55** [comment]
Thanks for the mongodb 4.2 suggestion. The mongodb starts up successfully
using "docker-compose -f docker-compose.yml up" with ":4.2" suffix on the
image name.
There are still authorization errors. Please see issue #238

What should I do now?

Thanks,
Bob

**Comment by azee** [comment]
@bobbeck55 Will address authorisation error in related ticket.
