### ISSUE TITLE
Quack user session appears to work BUT will not allow login

### ISSUE THREAD

**Issue by bobbeck55** [greatbit/quack#239]
**Describe the bug**
docker-compose -f docker-compose.yml up
(see docker-compose.yml, quack.properties, and quack_startup_log.txt)

**To Reproduce**
point browser to localhost
login as root
create user "bob"
list users
logout from root
attempt to login as "bob"

see session errors for "list users" even though the quack window shows the new "bob" user
see session errors for "login as bob" even though quack said it was created successfully

Environment:
Chrome browser
Ubuntu 22.04

**Comment by bobbeck55** [comment]
> ``

**Comment by bobbeck55** [comment]
Attaching to mongod, quack_quack_1
[36mmongod    |[0m 
[36mmongod    |[0m WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
[36mmongod    |[0m   see https://jira.mongodb.org/browse/SERVER-54407
[36mmongod    |[0m   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
[36mmongod    |[0m   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
[36mmongod    |[0m 
[36mmongod    |[0m 2023-02-20T20:12:04.193+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=b077d7843aa8
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] db version v4.2.23
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] git version: f4e6602d3a4c5b22e9d8bcf0722d0afd0ec01ea2
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] modules: none
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] build environment:
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten]     distarch: x86_64
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
[36mmongod    |[0m 2023-02-20T20:12:04.195+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
[36mmongod    |[0m 2023-02-20T20:12:04.196+0000 I  STORAGE  [initandlisten] 
[36mmongod    |[0m 2023-02-20T20:12:04.196+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[36mmongod    |[0m 2023-02-20T20:12:04.196+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[36mmongod    |[0m 2023-02-20T20:12:04.196+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1068M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
[36mmongod    |[0m 2023-02-20T20:12:04.377+0000 I  STORAGE  [initandlisten] WiredTiger message [1676923924:377000][1:0x7f487e414b00], txn-recover: Set global recovery timestamp: (0, 0)
[36mmongod    |[0m 2023-02-20T20:12:04.391+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
[36mmongod    |[0m 2023-02-20T20:12:04.407+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
[36mmongod    |[0m 2023-02-20T20:12:04.415+0000 I  CONTROL  [initandlisten] 
[36mmongod    |[0m 2023-02-20T20:12:04.415+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[36mmongod    |[0m 2023-02-20T20:12:04.415+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[36mmongod    |[0m 2023-02-20T20:12:04.415+0000 I  CONTROL  [initandlisten] 
[36mmongod    |[0m 2023-02-20T20:12:04.415+0000 I  STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 56cf34fe-93f7-4696-8031-415d57caf795 and options: { uuid: UUID("56cf34fe-93f7-4696-8031-415d57caf795") }
[36mmongod    |[0m 2023-02-20T20:12:04.433+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns admin.system.version
[36mmongod    |[0m 2023-02-20T20:12:04.433+0000 I  COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.2
[36mmongod    |[0m 2023-02-20T20:12:04.433+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
[36mmongod    |[0m 2023-02-20T20:12:04.433+0000 I  STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 442e6532-625a-48af-9c5a-7bbc2a6d9723 and options: { capped: true, size: 10485760 }
[36mmongod    |[0m 2023-02-20T20:12:04.452+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns local.startup_log
[36mmongod    |[0m 2023-02-20T20:12:04.453+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[36mmongod    |[0m 2023-02-20T20:12:04.455+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
[36mmongod    |[0m 2023-02-20T20:12:04.456+0000 I  NETWORK  [listener] Listening on 0.0.0.0
[36mmongod    |[0m 2023-02-20T20:12:04.456+0000 I  NETWORK  [listener] waiting for connections on port 27017
[36mmongod    |[0m 2023-02-20T20:12:04.456+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
[36mmongod    |[0m 2023-02-20T20:12:04.456+0000 I  STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with provided UUID: 68e198c0-a3bf-4e9b-9a35-7ef3255f39a7 and options: { uuid: UUID("68e198c0-a3bf-4e9b-9a35-7ef3255f39a7") }
[36mmongod    |[0m 2023-02-20T20:12:04.472+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index _id_ on ns config.system.sessions
[36mmongod    |[0m 2023-02-20T20:12:04.487+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: starting on config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 } using method: Hybrid
[36mmongod    |[0m 2023-02-20T20:12:04.487+0000 I  INDEX    [LogicalSessionCacheRefresh] build may temporarily use up to 200 megabytes of RAM
[36mmongod    |[0m 2023-02-20T20:12:04.487+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: collection scan done. scanned 0 total records in 0 seconds
[36mmongod    |[0m 2023-02-20T20:12:04.487+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: inserted 0 keys from external sorter into index in 0 seconds
[36mmongod    |[0m 2023-02-20T20:12:04.490+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index lsidTTLIndex on ns config.system.sessions
[33mquack_1   |[0m 2023-02-20 20:12:04.797:INFO::main: Logging initialized @103ms to org.eclipse.jetty.util.log.StdErrLog
[33mquack_1   |[0m WARNING: jetty-runner is deprecated.
[33mquack_1   |[0m          See Jetty Documentation for startup options
[33mquack_1   |[0m          https://www.eclipse.org/jetty/documentation/
[33mquack_1   |[0m 2023-02-20 20:12:04.803:INFO:oejr.Runner:main: Runner
[33mquack_1   |[0m 2023-02-20 20:12:04.875:INFO:oejs.Server:main: jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 1.8.0_212-b04
[33mquack_1   |[0m 2023-02-20 20:12:05.782:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
[33mquack_1   |[0m 2023-02-20 20:12:05.783:INFO:oejs.session:main: No SessionScavenger set, using defaults
[33mquack_1   |[0m 2023-02-20 20:12:05.787:INFO:oejs.session:main: node0 Scavenging every 660000ms
[33mquack_1   |[0m 2023-02-20 20:12:05.795:INFO:oejshC.ROOT:main: Initializing Spring root WebApplicationContext
[33mquack_1   |[0m 2023-02-20 20:12:05,855 [main                          ] INFO  ContextLoader                  - Root WebApplicationContext: initialization started
[33mquack_1   |[0m 2023-02-20 20:12:06,242 [main                          ] INFO  epositoryConfigurationDelegate - Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
[33mquack_1   |[0m 2023-02-20 20:12:06,397 [main                          ] INFO  epositoryConfigurationDelegate - Finished Spring Data repository scanning in 151 ms. Found 12 MongoDB repository interfaces.
[33mquack_1   |[0m 2023-02-20 20:12:06,824 [main                          ] INFO  egate$BeanPostProcessorChecker - Bean 'pluginsContainer' of type [ru.greatbit.plow.PluginsContainer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[33mquack_1   |[0m 2023-02-20 20:12:06,904 [main                          ] INFO  cluster                        - Cluster created with settings {hosts=[mongod:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[36mmongod    |[0m 2023-02-20T20:12:06.952+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:52378 #1 (1 connection now open)
[36mmongod    |[0m 2023-02-20T20:12:06.952+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:52362 #2 (2 connections now open)
[36mmongod    |[0m 2023-02-20T20:12:06.968+0000 I  NETWORK  [conn1] received client metadata from 172.18.0.3:52378 conn1: { driver: { name: "mongo-java-driver|sync", version: "4.4.0" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.19.0-31-generic" }, platform: "Java/Oracle Corporation/1.8.0_212-b04" }
[36mmongod    |[0m 2023-02-20T20:12:06.971+0000 I  NETWORK  [conn2] received client metadata from 172.18.0.3:52362 conn2: { driver: { name: "mongo-java-driver|sync", version: "4.4.0" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.19.0-31-generic" }, platform: "Java/Oracle Corporation/1.8.0_212-b04" }
[33mquack_1   |[0m 2023-02-20 20:12:06,980 [scription='null'}-mongod:27017] INFO  connection                     - Opened connection [connectionId{localValue:2, serverValue:1}] to mongod:27017
[33mquack_1   |[0m 2023-02-20 20:12:06,980 [scription='null'}-mongod:27017] INFO  connection                     - Opened connection [connectionId{localValue:1, serverValue:2}] to mongod:27017
[33mquack_1   |[0m 2023-02-20 20:12:06,981 [scription='null'}-mongod:27017] INFO  cluster                        - Monitor thread successfully connected to server with description ServerDescription{address=mongod:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=24624000}
[33mquack_1   |[0m 2023-02-20 20:12:07,100 [main                          ] WARN  CustomConversions              - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.instance.AddressPicker
[33mquack_1   |[0m INFO: [LOCAL] [dev] [5.0.2] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [127.0.0.1]
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.system.logo
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] 
[33mquack_1   |[0m 	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
[33mquack_1   |[0m 	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
[33mquack_1   |[0m 	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
[33mquack_1   |[0m 	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
[33mquack_1   |[0m 	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Hazelcast Platform 5.0.2 (20211221 - 18eec9f) starting at [127.0.0.1]:5903
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Cluster name: dev
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] The Jet engine is disabled.
[33mquack_1   |[0m To enable the Jet engine on the members, please do one of the following:
[33mquack_1   |[0m   - Change member config using Java API: config.getJetConfig().setEnabled(true);
[33mquack_1   |[0m   - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
[33mquack_1   |[0m   - Add system property: -Dhz.jet.enabled=true
[33mquack_1   |[0m   - Add environment variable: HZ_JET_ENABLED=true
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.system.security
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.instance.impl.Node
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Using TCP/IP discovery
[33mquack_1   |[0m Feb 20, 2023 8:12:07 PM com.hazelcast.cp.CPSubsystem
[33mquack_1   |[0m WARNING: [127.0.0.1]:5903 [dev] [5.0.2] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.diagnostics.Diagnostics
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.core.LifecycleService
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5903 is STARTING
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:08 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 20, 2023 8:12:09 PM com.hazelcast.internal.cluster.ClusterService
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] 
[33mquack_1   |[0m 
[33mquack_1   |[0m Members {size:1, ver:1} [
[33mquack_1   |[0m 	Member [127.0.0.1]:5903 - 9be368a0-cdf6-40ff-ad48-a4632dc589da this
[33mquack_1   |[0m ]
[33mquack_1   |[0m 
[33mquack_1   |[0m Feb 20, 2023 8:12:09 PM com.hazelcast.core.LifecycleService
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5903 is STARTED
[33mquack_1   |[0m Feb 20, 2023 8:12:09 PM com.hazelcast.internal.diagnostics.HealthMonitor
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] processors=3, physical.memory.total=3.1G, physical.memory.free=213.8M, swap.space.total=4.7G, swap.space.free=4.6G, heap.memory.used=185.7M, heap.memory.free=106.3M, heap.memory.total=292.0M, heap.memory.max=704.0M, heap.memory.used/total=63.61%, heap.memory.used/max=26.38%, minor.gc.count=14, minor.gc.time=69ms, major.gc.count=2, major.gc.time=104ms, load.process=0.00%, load.system=71.43%, load.systemAverage=0.55, thread.count=55, thread.peakCount=55, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
[33mquack_1   |[0m 2023-02-20 20:12:16,686 [main                          ] INFO  Version                        - HV000001: Hibernate Validator 5.2.4.Final
[33mquack_1   |[0m 2023-02-20 20:12:16,739 [main                          ] WARN  CustomConversions              - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
[33mquack_1   |[0m 2023-02-20 20:12:16,757 [main                          ] INFO  ContextLoader                  - Root WebApplicationContext initialized in 10902 ms
[33mquack_1   |[0m 2023-02-20 20:12:17,005 [main                          ] INFO  Reflections                    - Reflections took 30 ms to scan 1 urls, producing 43 keys and 77 values 
[33mquack_1   |[0m Feb 20, 2023 8:12:17 PM org.glassfish.jersey.internal.Errors logErrors
[33mquack_1   |[0m WARNING: The following warnings have been detected: WARNING: The (sub)resource method getLaunchersList in com.testquack.api.resources.LauncherResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method createUser in com.testquack.api.resources.UserResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method updateUser in com.testquack.api.resources.UserResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.UserResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.LaunchResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.LaunchResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.LaunchResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m 
[33mquack_1   |[0m 2023-02-20 20:12:17.456:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@44e81672{/,file:///tmp/jetty-0_0_0_0-8080-quack_war-_-any-3495388969529540879/webapp/,AVAILABLE}{file:///usr/quack/quack.war}
[33mquack_1   |[0m 2023-02-20 20:12:17.462:INFO:oejs.AbstractConnector:main: Started ServerConnector@11028347{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[33mquack_1   |[0m 2023-02-20 20:12:17.463:INFO:oejs.Server:main: Started @12774ms
[33mquack_1   |[0m 2023-02-20 20:12:45,604 [qtp815033865-12               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[36mmongod    |[0m 2023-02-20T20:12:48.082+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:54230 #3 (3 connections now open)
[36mmongod    |[0m 2023-02-20T20:12:48.083+0000 I  NETWORK  [conn3] received client metadata from 172.18.0.3:54230 conn3: { driver: { name: "mongo-java-driver|sync", version: "4.4.0" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.19.0-31-generic" }, platform: "Java/Oracle Corporation/1.8.0_212-b04" }
[33mquack_1   |[0m 2023-02-20 20:12:48,086 [qtp815033865-12               ] INFO  connection                     - Opened connection [connectionId{localValue:4, serverValue:3}] to mongod:27017
[36mmongod    |[0m 2023-02-20T20:12:48.084+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:54242 #4 (4 connections now open)
[36mmongod    |[0m 2023-02-20T20:12:48.091+0000 I  NETWORK  [conn4] received client metadata from 172.18.0.3:54242 conn4: { driver: { name: "mongo-java-driver|sync", version: "4.4.0" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.19.0-31-generic" }, platform: "Java/Oracle Corporation/1.8.0_212-b04" }
[33mquack_1   |[0m 2023-02-20 20:12:48,095 [qtp815033865-16               ] INFO  connection                     - Opened connection [connectionId{localValue:3, serverValue:4}] to mongod:27017
[36mmongod    |[0m 2023-02-20T20:13:09.145+0000 I  STORAGE  [conn3] createCollection: test.users with generated UUID: 17f4c518-6e1b-4279-86ca-b09900ed8819 and options: {}
[36mmongod    |[0m 2023-02-20T20:13:09.162+0000 I  INDEX    [conn3] index build: done building index _id_ on ns test.users
[33mquack_1   |[0m Feb 20, 2023 8:13:09 PM com.hazelcast.internal.diagnostics.HealthMonitor
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] processors=3, physical.memory.total=3.1G, physical.memory.free=78.7M, swap.space.total=4.7G, swap.space.free=4.6G, heap.memory.used=237.7M, heap.memory.free=68.3M, heap.memory.total=306.0M, heap.memory.max=704.0M, heap.memory.used/total=77.67%, heap.memory.used/max=33.76%, minor.gc.count=17, minor.gc.time=149ms, major.gc.count=3, major.gc.time=192ms, load.process=0.00%, load.system=0.00%, load.systemAverage=0.62, thread.count=60, thread.peakCount=60, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
[33mquack_1   |[0m 2023-02-20 20:14:18,258 [qtp815033865-16               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-20 20:14:36,104 [qtp815033865-14               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
Gracefully stopping... (press Ctrl+C again to force)

**Comment by bobbeck55** [comment]
whoru.auth.provider=com.testquack.api.security.DbAuthProvider
whoru.session.provider=ru.greatbit.whoru.auth.providers.HazelcastSessionProvider
stub.login=bob
stub.password=jean
auth.domain=10.0.2.15
auth.session.ttl=6000000
auth.admin.login=root
auth.admin.password=rootpass
auth.admin.token=abc

#Hazelcast
entity.lock.ttl.min=5
hazelcast.group.name=dev
hazelcast.group.password=dev-pass
hazelcast.ttl.sec=1209600
hazelcast.port=5903
hazelcast.port.rest=5904
hazelcast.port.auto.increment=true
hazelcast.members=10.0.2.15
hazelcast.interface=10.0.2.15
hazelcast.backup.count=1
hazelcast.prefer.ipv4.stack=true
hazelcast.aws.enabled=false
hazelcast.tcpip.enabled=true

#Storage
storage.provider=com.testquack.storage.MongoStorage

#Tracker
quack.tracker=com.testquack.tracker.DummyTracker

quack.multi.organization.mode=false

#Properties in case CognitoAuthProvider is being used
aws.cognito.access.key=CHANGEME
aws.cognito.secret.key=CHANGEME
aws.cognito.region=us-east-1
aws.cognito.oauth.endpoint=
aws.cognito.client.id=CHANGEME
aws.cognito.redirect.url=
cognito-auth-provider=
cognito.login.url=

quack.organizations.enabled=false
quack.organization.default.sessions.capacity=3

google.analytics.enabled=false

**Comment by bobbeck55** [comment]
version: '2'
services:
  quack:
    image: greatbit/quack-api
    ports:
      - "8080:8080"
      - "81:81"
    links:
      - mongod
    depends_on:
      - mongod

  mongod:
    container_name: "mongod"
    image: mongo
    ports:
      - "27017:27017"

**Comment by bobbeck55** [comment]
FYI - The same results occur if I use localhost, 127.0.0.1, or the actual local ip address.

**Comment by azee** [comment]
1. Make sure that auth.domain=10.0.2.15 matches what you are entering in the browser. E.g., if you are accessing quack UI using port 8080, like http://10.0.2.15:8080, then auth domain should reflect that
 auth.domain=10.0.2.15:8080

Alternatively you can set up ports like
ports:
- "80:8080"

You'll be able to access quack via http://10.0.2.15 and auth.domain can stay as in your example - auth.domain=10.0.2.15

2. If that won't help. Might be related to Hazelcast setup.

Lets try the following - replace
whoru.session.provider=ru.greatbit.whoru.auth.providers.HazelcastSessionProvider
with 
whoru.session.provider=ru.greatbit.whoru.auth.providers.InmemSessionProvider

Try to restart the app and run again.

If this will help - you can try returning back Hazelcast provider and point it to itself
hazelcast.members=127.0.0.1
hazelcast.interface=127.0.0.1

However, if you are running only a single instance if quack service, you don't need hazelcast. Inmem provider will do just fine.

**Comment by bobbeck55** [comment]
I can now create users, projects, and tests when logged in to localhost BUT
not if I use an actual ip address. Can I chat you sometime? Maybe this
afternoon or tomorrow
morning?It would speed up this process.

Bob

**Comment by bobbeck55** [comment]
Working now for localhost. See issue #240. Now I want to get it to work
when i point my browser to the ip address and I want
anything I create (db, user, test case) to be persisted.

Bob
