### ISSUE TITLE
Unable to do root login with config change for persistence

### ISSUE THREAD

**Issue by bobbeck55** [greatbit/quack#245]
Changed docker-compose.yml - added your suggestions.
Ran with 2 quack.properties - identifed as test1 and test2 in file in a soon to come comment.
Pointed browser to ip address. Unable to login as root. Could not save picture of error since it appeared and disappeared so quickly.
Both config files and logs will be added to this issue soon.

**Comment by bobbeck55** [comment]
docker-compose.yml
---------------------------
version: '2'
services:
  quack:
    image: greatbit/quack
    ports:
      - "80:80"
    links:
      - mongod:mongod
    depends_on:
      - mongod
    environment:
      WAIT_HOSTS: mongod:27017
    volumes:
      - /home/bob/quack_db:/etc/quack
    volumes:
      - /data/db:/data/db

  mongod:
    container_name: "mongod"
    image: mongo:4.2
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
    - /data/db:/data/db
quack.properties
-----------------------
#Database
mongo.replicaSet=mongod:27017
mongo.dbname=test
mongo.username=
mongo.password=
mongo.uri=
#Authentication
# "Couldn't save project for created user, works for root", auth works
# test 1
#whoru.auth.provider=com.testquack.api.security.DbAuthProvider
#whoru.session.provider=ru.greatbit.whoru.auth.providers.InmemSessionProvider
#auth.domain=192.168.56.102
# test 2
# auth combo works - creates user, logout/login works, create project works for root,
# not for created user
whoru.auth.provider=com.testquack.api.security.DbAuthProvider
whoru.session.provider=ru.greatbit.whoru.auth.providers.HazelcastSessionProvider
auth.domain=192.168.56.102
#combo1 works
#whoru.auth.provider=ru.greatbit.whoru.auth.providers.StubAuthProvider
#whoru.session.provider=ru.greatbit.whoru.auth.providers.InmemSessionProvider
#auth.domain=localhost:80
#combo2 works
#whoru.session.provider=ru.greatbit.whoru.auth.providers.HazelcastSessionProvider
#auth.domain=localhost:80
# doesn't work
#whoru.auth.provider=ru.greatbit.whoru.auth.providers.StubAuthProvider
#auth.domain=192.168.56.102:80
# doesn't work
#whoru.auth.provider=ru.greatbit.whoru.auth.providers.InmemSessionProvider
#auth.domain=192.168.56.102:80
# doesn't work
#whoru.auth.provider=com.testquack.api.security.DbAuthProvider
#auth.domain=192.168.56.102:80
# doesn't work
#whoru.session.provider=ru.greatbit.whoru.auth.providers.HazelcastSessionProvider
#auth.domain=192.168.56.102:80
stub.login=someuser
stub.password=somepassword
#auth.domain=localhost:80
auth.session.ttl=6000000
auth.admin.login=root
auth.admin.password=rootpass
auth.admin.token=abc
auth.admin.logins=azee,zyxel560k@mail.ru
#Hazelcast
entity.lock.ttl.min=5
hazelcast.group.name=dev
hazelcast.group.password=dev-pass
hazelcast.ttl.sec=1209600
hazelcast.port=5903
hazelcast.port.rest=5904
hazelcast.port.auto.increment=true
hazelcast.members=127.0.0.1
hazelcast.interface=127.0.0.1
hazelcast.backup.count=1
hazelcast.prefer.ipv4.stack=true
hazelcast.aws.enabled=false
hazelcast.tcpip.enabled=true
storage.provider=com.testquack.storage.MongoStorage
quack.tracker=com.testquack.tracker.DummyTracker
aws.cognito.access.key=CHANGEME
aws.cognito.secret.key=CHANGEME
aws.cognito.region=us-east-1
aws.cognito.oauth.endpoint=
aws.cognito.client.id=CHANGEME
aws.cognito.redirect.url=
cognito-auth-provider=
cognito.login.url=

log
----
Attaching to mongod, quack_quack_1
[36mmongod    |[0m 
[36mmongod    |[0m WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
[36mmongod    |[0m   see https://jira.mongodb.org/browse/SERVER-54407
[36mmongod    |[0m   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
[36mmongod    |[0m   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
[36mmongod    |[0m 
[36mmongod    |[0m 2023-02-24T15:38:35.822+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
[36mmongod    |[0m 2023-02-24T15:38:35.826+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=685dd806d1c3
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] db version v4.2.23
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] git version: f4e6602d3a4c5b22e9d8bcf0722d0afd0ec01ea2
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] modules: none
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] build environment:
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten]     distarch: x86_64
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
[36mmongod    |[0m 2023-02-24T15:38:35.827+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
[36mmongod    |[0m 2023-02-24T15:38:35.828+0000 W  STORAGE  [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
[36mmongod    |[0m 2023-02-24T15:38:35.828+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[36mmongod    |[0m 2023-02-24T15:38:35.828+0000 W  STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
[36mmongod    |[0m 2023-02-24T15:38:35.828+0000 I  STORAGE  [initandlisten] 
[36mmongod    |[0m 2023-02-24T15:38:35.828+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[36mmongod    |[0m 2023-02-24T15:38:35.828+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[36mmongod    |[0m 2023-02-24T15:38:35.828+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1068M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
[36mmongod    |[0m 2023-02-24T15:38:35.980+0000 I  STORAGE  [initandlisten] WiredTiger message [1677253115:980297][1:0x7effecbf9b00], txn-recover: Recovering log 3 through 4
[36mmongod    |[0m 2023-02-24T15:38:36.038+0000 I  STORAGE  [initandlisten] WiredTiger message [1677253116:38124][1:0x7effecbf9b00], txn-recover: Recovering log 4 through 4
[36mmongod    |[0m 2023-02-24T15:38:36.109+0000 I  STORAGE  [initandlisten] WiredTiger message [1677253116:109634][1:0x7effecbf9b00], txn-recover: Main recovery loop: starting at 3/3200 to 4/256
[36mmongod    |[0m 2023-02-24T15:38:36.111+0000 I  STORAGE  [initandlisten] WiredTiger message [1677253116:111943][1:0x7effecbf9b00], txn-recover: Recovering log 3 through 4
[36mmongod    |[0m 2023-02-24T15:38:36.181+0000 I  STORAGE  [initandlisten] WiredTiger message [1677253116:181471][1:0x7effecbf9b00], file:sizeStorer.wt, txn-recover: Recovering log 4 through 4
[36mmongod    |[0m 2023-02-24T15:38:36.230+0000 I  STORAGE  [initandlisten] WiredTiger message [1677253116:230085][1:0x7effecbf9b00], file:sizeStorer.wt, txn-recover: Set global recovery timestamp: (0, 0)
[36mmongod    |[0m 2023-02-24T15:38:36.271+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
[36mmongod    |[0m 2023-02-24T15:38:36.272+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
[36mmongod    |[0m 2023-02-24T15:38:36.275+0000 I  CONTROL  [initandlisten] 
[36mmongod    |[0m 2023-02-24T15:38:36.275+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[36mmongod    |[0m 2023-02-24T15:38:36.275+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[36mmongod    |[0m 2023-02-24T15:38:36.275+0000 I  CONTROL  [initandlisten] 
[36mmongod    |[0m 2023-02-24T15:38:36.278+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
[36mmongod    |[0m 2023-02-24T15:38:36.284+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[36mmongod    |[0m 2023-02-24T15:38:36.287+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
[36mmongod    |[0m 2023-02-24T15:38:36.287+0000 I  NETWORK  [listener] Listening on 0.0.0.0
[36mmongod    |[0m 2023-02-24T15:38:36.287+0000 I  NETWORK  [listener] waiting for connections on port 27017
[33mquack_1   |[0m 2023-02-24 15:38:36.589:INFO::main: Logging initialized @115ms to org.eclipse.jetty.util.log.StdErrLog
[33mquack_1   |[0m WARNING: jetty-runner is deprecated.
[33mquack_1   |[0m          See Jetty Documentation for startup options
[33mquack_1   |[0m          https://www.eclipse.org/jetty/documentation/
[33mquack_1   |[0m 2023-02-24 15:38:36.594:INFO:oejr.Runner:main: Runner
[33mquack_1   |[0m 2023-02-24 15:38:36.666:INFO:oejs.Server:main: jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 1.8.0_212-b04
[36mmongod    |[0m 2023-02-24T15:38:37.003+0000 I  FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
[33mquack_1   |[0m 2023-02-24 15:38:37.570:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
[33mquack_1   |[0m 2023-02-24 15:38:37.570:INFO:oejs.session:main: No SessionScavenger set, using defaults
[33mquack_1   |[0m 2023-02-24 15:38:37.573:INFO:oejs.session:main: node0 Scavenging every 660000ms
[33mquack_1   |[0m 2023-02-24 15:38:37.579:INFO:oejshC.ROOT:main: Initializing Spring root WebApplicationContext
[33mquack_1   |[0m 2023-02-24 15:38:37,620 [main                          ] INFO  ContextLoader                  - Root WebApplicationContext: initialization started
[33mquack_1   |[0m 2023-02-24 15:38:37,957 [main                          ] INFO  epositoryConfigurationDelegate - Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
[33mquack_1   |[0m 2023-02-24 15:38:38,060 [main                          ] INFO  epositoryConfigurationDelegate - Finished Spring Data repository scanning in 99 ms. Found 12 MongoDB repository interfaces.
[33mquack_1   |[0m 2023-02-24 15:38:38,393 [main                          ] INFO  egate$BeanPostProcessorChecker - Bean 'pluginsContainer' of type [ru.greatbit.plow.PluginsContainer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[33mquack_1   |[0m 2023-02-24 15:38:38,479 [main                          ] INFO  cluster                        - Cluster created with settings {hosts=[mongod:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[36mmongod    |[0m 2023-02-24T15:38:38.527+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:60474 #1 (1 connection now open)
[36mmongod    |[0m 2023-02-24T15:38:38.527+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:60476 #2 (2 connections now open)
[36mmongod    |[0m 2023-02-24T15:38:38.538+0000 I  NETWORK  [conn1] received client metadata from 172.18.0.3:60474 conn1: { driver: { name: "mongo-java-driver|sync", version: "4.4.0" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.19.0-31-generic" }, platform: "Java/Oracle Corporation/1.8.0_212-b04" }
[36mmongod    |[0m 2023-02-24T15:38:38.538+0000 I  NETWORK  [conn2] received client metadata from 172.18.0.3:60476 conn2: { driver: { name: "mongo-java-driver|sync", version: "4.4.0" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "5.19.0-31-generic" }, platform: "Java/Oracle Corporation/1.8.0_212-b04" }
[33mquack_1   |[0m 2023-02-24 15:38:38,558 [scription='null'}-mongod:27017] INFO  connection                     - Opened connection [connectionId{localValue:2, serverValue:1}] to mongod:27017
[33mquack_1   |[0m 2023-02-24 15:38:38,558 [scription='null'}-mongod:27017] INFO  connection                     - Opened connection [connectionId{localValue:1, serverValue:2}] to mongod:27017
[33mquack_1   |[0m 2023-02-24 15:38:38,559 [scription='null'}-mongod:27017] INFO  cluster                        - Monitor thread successfully connected to server with description ServerDescription{address=mongod:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=27199398}
[33mquack_1   |[0m 2023-02-24 15:38:38,681 [main                          ] WARN  CustomConversions              - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
[33mquack_1   |[0m Feb 24, 2023 3:38:38 PM com.hazelcast.instance.AddressPicker
[33mquack_1   |[0m INFO: [LOCAL] [dev] [5.0.2] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [127.0.0.1]
[33mquack_1   |[0m Feb 24, 2023 3:38:38 PM com.hazelcast.system.logo
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] 
[33mquack_1   |[0m 	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
[33mquack_1   |[0m 	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
[33mquack_1   |[0m 	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
[33mquack_1   |[0m 	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
[33mquack_1   |[0m 	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
[33mquack_1   |[0m Feb 24, 2023 3:38:38 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
[33mquack_1   |[0m Feb 24, 2023 3:38:38 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Hazelcast Platform 5.0.2 (20211221 - 18eec9f) starting at [127.0.0.1]:5903
[33mquack_1   |[0m Feb 24, 2023 3:38:38 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Cluster name: dev
[33mquack_1   |[0m Feb 24, 2023 3:38:38 PM com.hazelcast.system
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] The Jet engine is disabled.
[33mquack_1   |[0m To enable the Jet engine on the members, please do one of the following:
[33mquack_1   |[0m   - Change member config using Java API: config.getJetConfig().setEnabled(true);
[33mquack_1   |[0m   - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
[33mquack_1   |[0m   - Add system property: -Dhz.jet.enabled=true
[33mquack_1   |[0m   - Add environment variable: HZ_JET_ENABLED=true
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.system.security
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.instance.impl.Node
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Using TCP/IP discovery
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.cp.CPSubsystem
[33mquack_1   |[0m WARNING: [127.0.0.1]:5903 [dev] [5.0.2] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.internal.diagnostics.Diagnostics
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.core.LifecycleService
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5903 is STARTING
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:39 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:40 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5904 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:40 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5905 is added to the blacklist.
[33mquack_1   |[0m Feb 24, 2023 3:38:40 PM com.hazelcast.internal.cluster.ClusterService
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] 
[33mquack_1   |[0m 
[33mquack_1   |[0m Members {size:1, ver:1} [
[33mquack_1   |[0m 	Member [127.0.0.1]:5903 - 17157314-fb3f-4cf4-8e03-e11f0835ae7a this
[33mquack_1   |[0m ]
[33mquack_1   |[0m 
[33mquack_1   |[0m Feb 24, 2023 3:38:40 PM com.hazelcast.core.LifecycleService
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] [127.0.0.1]:5903 is STARTED
[33mquack_1   |[0m Feb 24, 2023 3:38:40 PM com.hazelcast.internal.diagnostics.HealthMonitor
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] processors=3, physical.memory.total=3.1G, physical.memory.free=561.7M, swap.space.total=4.7G, swap.space.free=4.5G, heap.memory.used=185.6M, heap.memory.free=109.9M, heap.memory.total=295.5M, heap.memory.max=704.0M, heap.memory.used/total=62.81%, heap.memory.used/max=26.36%, minor.gc.count=11, minor.gc.time=73ms, major.gc.count=2, major.gc.time=64ms, load.process=100.00%, load.system=50.00%, load.systemAverage=0.26, thread.count=54, thread.peakCount=54, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
[33mquack_1   |[0m 2023-02-24 15:38:47,998 [main                          ] INFO  Version                        - HV000001: Hibernate Validator 5.2.4.Final
[33mquack_1   |[0m 2023-02-24 15:38:48,060 [main                          ] WARN  CustomConversions              - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
[33mquack_1   |[0m 2023-02-24 15:38:48,082 [main                          ] INFO  ContextLoader                  - Root WebApplicationContext initialized in 10461 ms
[33mquack_1   |[0m 2023-02-24 15:38:48,613 [main                          ] INFO  Reflections                    - Reflections took 86 ms to scan 1 urls, producing 43 keys and 77 values 
[33mquack_1   |[0m Feb 24, 2023 3:38:49 PM org.glassfish.jersey.internal.Errors logErrors
[33mquack_1   |[0m WARNING: The following warnings have been detected: WARNING: The (sub)resource method getLaunchersList in com.testquack.api.resources.LauncherResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method createUser in com.testquack.api.resources.UserResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method updateUser in com.testquack.api.resources.UserResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.UserResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.AttributeResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.CommentResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.EventResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.LaunchResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.LaunchResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.LaunchResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.TestSuiteResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method findFiltered in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method update in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method delete in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m WARNING: The (sub)resource method create in com.testquack.api.resources.TestCaseResource contains empty path annotation.
[33mquack_1   |[0m 
[33mquack_1   |[0m 2023-02-24 15:38:49.551:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@44e81672{/,file:///tmp/jetty-0_0_0_0-8080-quack_war-_-any-4858531794210175598/webapp/,AVAILABLE}{file:///usr/quack/quack.war}
[33mquack_1   |[0m 2023-02-24 15:38:49.562:INFO:oejs.AbstractConnector:main: Started ServerConnector@11028347{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[33mquack_1   |[0m 2023-02-24 15:38:49.562:INFO:oejs.Server:main: Started @13092ms
[33mquack_1   |[0m 2023-02-24 15:38:52,471 [qtp815033865-12               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:38:53,276 [qtp815033865-9                ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:38:53,560 [qtp815033865-16               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:38:56,747 [qtp815033865-13               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:38:57,212 [qtp815033865-11               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:38:57,558 [qtp815033865-11               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:39:00,257 [qtp815033865-16               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:39:00,494 [qtp815033865-69               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m Feb 24, 2023 3:39:00 PM com.hazelcast.internal.diagnostics.HealthMonitor
[33mquack_1   |[0m INFO: [127.0.0.1]:5903 [dev] [5.0.2] processors=3, physical.memory.total=3.1G, physical.memory.free=68.6M, swap.space.total=4.7G, swap.space.free=4.5G, heap.memory.used=167.1M, heap.memory.free=134.9M, heap.memory.total=302.0M, heap.memory.max=704.0M, heap.memory.used/total=55.34%, heap.memory.used/max=23.74%, minor.gc.count=14, minor.gc.time=124ms, major.gc.count=3, major.gc.time=156ms, load.process=0.00%, load.system=100.00%, load.systemAverage=1.00, thread.count=61, thread.peakCount=61, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
[33mquack_1   |[0m 2023-02-24 15:39:00,886 [qtp815033865-11               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:39:03,471 [qtp815033865-69               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:39:03,770 [qtp815033865-69               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize
[33mquack_1   |[0m 2023-02-24 15:39:04,140 [qtp815033865-11               ] INFO  ExceptionHandler               - User session not found and will be prompt to authorize

**Comment by azee** [comment]
Looks good, @bobbeck55 . Mongo data will be stored under data folder on your local machine. And again, for a multi-user production level application you'll need a real mongo replica set for consistency and sustainability.
