### ISSUE TITLE
Broken with docker-compose

### ISSUE THREAD

**Issue by 32h** [greatbit/quack#95]
Has many HTTP 503 in requests.
Cant login.
Cant anything.

![Снимок экрана от 2019-09-12 09-50-21](https://user-images.githubusercontent.com/3368580/64760623-d59e7400-d542-11e9-99a8-fc5a2e37606e.png)

**Comment by azee** [comment]
I assume you used 
docker-compose up - this will work if you have your own mongo configured
If you want a complete compose with demo database - use
docker-compose -f docker-compose-demo.yml up

I'll update README

**Comment by azee** [comment]
There was an error in mongo image name. Service couldn't resolve corresponding host in config file. Fixed.

I'd recommend using 
docker-compose -f docker-compose-demo.yml up
it has some initial test-project
